# Generated by Django 6.0.6 on 2026-07-26 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Cloud Energy Photoelectric Ltd', max_length=200)),
                ('company_email', models.EmailField(blank=True, max_length=254)),
                ('company_phone', models.CharField(blank=True, max_length=30)),
                ('website', models.URLField(blank=True)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company/')),
                ('currency', models.CharField(default='NGN', max_length=10)),
                ('quotation_prefix', models.CharField(default='QT-', max_length=10)),
                ('invoice_prefix', models.CharField(default='INV-', max_length=10)),
                ('default_backup_hours', models.PositiveIntegerField(default=8)),
                ('safety_margin', models.DecimalField(decimal_places=2, default=25, max_digits=5)),
                ('default_voltage', models.PositiveIntegerField(default=230)),
                ('email_notifications', models.BooleanField(default=True)),
                ('google_maps_api_key', models.CharField(blank=True, max_length=255)),
                ('weather_api_key', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'System')], default='light', max_length=20)),
                ('email_notifications', models.BooleanField(default=True)),
                ('browser_notifications', models.BooleanField(default=True)),
                ('assessment_alerts', models.BooleanField(default=True)),
                ('customer_alerts', models.BooleanField(default=True)),
                ('weekly_summary', models.BooleanField(default=False)),
                ('show_dashboard_stats', models.BooleanField(default=True)),
                ('show_recent_assessments', models.BooleanField(default=True)),
                ('show_recent_customers', models.BooleanField(default=True)),
                ('show_quick_actions', models.BooleanField(default=True)),
                ('language', models.CharField(default='English', max_length=50)),
                ('timezone', models.CharField(default='Africa/Lagos', max_length=100)),
                ('date_format', models.CharField(choices=[('dd/mm/yyyy', 'DD/MM/YYYY'), ('mm/dd/yyyy', 'MM/DD/YYYY'), ('yyyy-mm-dd', 'YYYY-MM-DD')], default='dd/mm/yyyy', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('employee_id', models.CharField(blank=True, max_length=50)),
                ('job_title', models.CharField(blank=True, max_length=100)),
                ('biography', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
