# Generated by Django 6.0.6 on 2026-07-26 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemsetting',
            options={'permissions': [('manage_system_settings', 'Can manage system settings')], 'verbose_name': 'System Setting', 'verbose_name_plural': 'System Settings'},
        ),
    ]
