# Generated by Django 6.0.6 on 2026-08-04 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0004_appliance_library_appliance_delete_assessmentitem'),
        ('crm', '0002_salesprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='assigned_sales',
            field=models.ForeignKey(blank=True, help_text='Sales consultant responsible for this assessment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to='crm.salesprofile'),
        ),
    ]
