# Generated by Django 6.0.6 on 2026-08-05 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0005_assessment_assigned_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='reference',
            field=models.CharField(blank=True, editable=False, max_length=25),
        ),
    ]
