# Generated by Django 6.0.6 on 2026-08-05 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0006_assessment_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='reference',
            field=models.CharField(blank=True, editable=False, max_length=25, unique=True),
        ),
    ]
