# Generated by Django 6.0.6 on 2026-08-17 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audits", "0007_alter_assessment_reference"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="existing_battery_capacity",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Existing battery capacity in kWh.",
                max_digits=8,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="existing_inverter_capacity",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Existing inverter capacity in kVA.",
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="generator_available",
            field=models.BooleanField(
                default=False, verbose_name="Generator Available"
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="generator_capacity",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Generator capacity in kVA.",
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="grid_available",
            field=models.BooleanField(
                default=True, verbose_name="Connected to Public Grid"
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="has_existing_battery",
            field=models.BooleanField(
                default=False, verbose_name="Existing Battery Bank"
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="has_existing_inverter",
            field=models.BooleanField(default=False, verbose_name="Existing Inverter"),
        ),
        migrations.AddField(
            model_name="assessment",
            name="has_existing_solar",
            field=models.BooleanField(
                default=False, verbose_name="Existing Solar System"
            ),
        ),
    ]
