# Generated by Django 6.0.6 on 2026-10-04 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audits", "0008_assessment_existing_battery_capacity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessment",
            name="system_voltage",
            field=models.PositiveIntegerField(
                choices=[
                    (12, "12 Volts"),
                    (24, "24 Volts"),
                    (48, "48 Volts"),
                    (96, "96 Volts"),
                ],
                default=48,
            ),
        ),
    ]
