# Generated by Django 6.0.6 on 2026-10-04 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audits", "0009_alter_assessment_system_voltage"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="customer_confirmation_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="assessment",
            name="customer_confirmation_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
